### ISSUE TITLE
게시글 찜 조회, 찜 등록 / 등록 해제 오류

### ISSUE THREAD

**Issue by choi5798** [Dcom-KHU/nearbuy-backend#29]
구현을 다 하고 테스트를 해봤더니 에러가 떴음
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/22406453/227707898-cc91c033-6e4e-437a-9e67-0758e09868c5.png">
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/22406453/227707919-606bb0d9-e533-4162-ab17-80c8ecb9ea04.png">
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/22406453/227707943-14adcf9d-fb66-42e7-ac9e-7d6c8da307e4.png">
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/22406453/227707959-88d74abb-70f2-4c0c-8213-031bc87de41b.png">
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/22406453/227707978-222183c1-c6c6-47cb-8d15-371344f9d60d.png">
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/22406453/227707986-9dfd66dd-7982-4e86-8d73-c39abf9e53f2.png">

등록이 안되서 일단 DB에 수동으로 UserLike table에 값을 넣어준 후 조회를 했더니 위 이미지와 같은 에러가 떴음
등록 / 등록 해제 api 를 호출해도 똑같은 에러가 뜹니다

구글링 했더니 상속관계에서 나타나는 에러라는데 무엇이 문제일까요?

수정사항이 적용된 파일들 다 푸쉬해놓은 상태입니다

- 참고파일
- api/domain/post/controller/PostController.java
- api/domain/post/service/PostService.java

**Comment by lomayd** [comment]
API 호출이 아닌 로컬 DB에 수동으로 값을 집어넣을 때 Discriminator Type 값에 문제가 생겨 발생한 오류로 보이며, API 호출을 통해 게시글을 생성하고 UserLike 관련 API를 호출하니 정상적으로 작동하는 것을 확인했습니다.
